### PR TITLE
Handle GD warnings on loading corrupted images in GDImageAdapter

### PR DESCRIPTION
**Pull request by othmar52**
a [sliMpd](https://github.com/othmar52/slimpd) user [reported an error](https://github.com/othmar52/slimpd/issues/44#issuecomment-266333393) caused by color-thief-php. Unfortunately i was not able to reproduce it but in theory this changes should do the trick!?

### CODE REVIEW

**Comment by ksubileau** [comment]
Hi,
First of all, thank you for your bug report and congratulations for your really interesting project ! :)

Indeed, I think we need to find why you can't to reproduce this error and isolate a sample image allowing me to check that the fix works. Have you check that Imagick and Gmagick extensions were disabled or not installed on your test bench, so that the GD Image Adapter is selected by Color Thief ? If one of these two extensions is available, Color Thief will use it instead of GD and the suspected piece of code will not be executed (see [here](https://github.com/ksubileau/color-thief-php/blob/097c3e6bde0252069c8b8873032ef4839b022d23/lib/ColorThief/Image/ImageLoader.php#L16)). Maybe you can ask a phpinfo output to your user and compare with yours.

But in theory the proposed fix here do nothing more than the try/catch statement you put directly in your project, so I'm afraid it will not work better. I would rather say that we need to put a `@` character before each call to imagecreatefromXXX in the switch/case statement to mute the fatal error, and after that throw an exception if `$this->resource` is equal to `false`, something like that :
```php
    public function loadFile($file)
    {
        list(, , $type) = @getImageSize($file);
        $resource = false;
        switch ($type) {
            case IMAGETYPE_GIF:
                $resource = @imagecreatefromgif($file);
                break;
            case IMAGETYPE_JPEG:
                $resource = @imagecreatefromjpeg($file);
                break;
            case IMAGETYPE_PNG:
                $resource = @imagecreatefrompng($file);
                break;
        }
        if ($resource === false) {
            throw new \RuntimeException("Error loading image: the file '".$file."' is not readable, corrupted, or does not exists.");
        }
        $this->resource = $resource;
    }
```

But I'll wait for a sample image to write the proper test case and find the right fix :)

**Comment by othmar52** [comment]
> But in theory the proposed fix here do nothing more than the try/catch
> statement you put directly in your project, so I'm afraid it will not work better. 

Thats not true. With try/catch blocks you can only catch thrown Exceptions. A FATAL ERROR is not catchable and simply causes the script to stop. Supressing the error with `@` is very bad practice imho.

Without a thrown exception i am not able to use my ["backup code"](https://github.com/othmar52/slimpd/blob/master/core/php/Modules/Importer/Filescanner.php#L263) in case something goes wrong.

**Conclusion** Technically i am not able to fix the error on the sliMpd side. Or am i wrong?

**Comment by ksubileau** [comment]
> Thats not true. With try/catch blocks you can only catch thrown Exceptions. A FATAL ERROR of color-thief is not catchable on the sliMpd side and simply causes the script to stop.

Maybe I was not clear enough, sorry. You're totally right, a try/catch block can only catch thrown **Exceptions**, not warnings or errors of GD library (`imagecreatefromjpeg`) like those [reported by @clkmsc](https://github.com/othmar52/slimpd/issues/44#issuecomment-266333393). So the try/catch block you add around `imagecreatefromjpeg ` call inside color-thief will not catch those GD warnings/errors, that's why I said the proposed fix here do nothing more, i.e it does not solve the problem.

Therefore, it is necessary to mute the GD errors with `@` (indeed, a bad practice but only if used inappropriately) and then check the return value to see if an error was encountered.

I managed to reproduce the problem with a corrupted JPG (by cutting a JPG file in the middle) and with the file [retrieved by @clkmsc](https://github.com/othmar52/slimpd/issues/44#issuecomment-266898940). 
My first tests seem to confirm that the code proposed in my previous answer could do the trick.

**Comment by othmar52** [comment]
thanks to @clkmsc i was able to reproduce the error as well. now everything works as expected and i am able to catch the exception outside of your fantastic library.

I pushed the cleaner version into my pull-request-branch. Hopefully you will release a new version of color-thief-php soon.
Thank you very much for your support and explainations.

**Comment by ksubileau** [comment]
Finally I changed the code a little to keep the distinction between the two error cases (unknown type vs reading failure), and I rewrote the Git history to make it a little clearer.

**Comment by ksubileau** [comment]
FYI, version 1.3.1 is out !

**Pull request merged**
